### ISSUE TITLE
How to get readerID in humain readable format from GET_READER_CONFIG_RESPONSE

### ISSUE THREAD

**Issue by iamadou** [enilink/llrp4j#8]
Hi!

I'm trying to get the reader MAC address from reader configuration response, but with the method readerID(), the return value is unreadable format, I can someone know how to convert the Unsigned Bytes Array_Hex to int.

Thanks

**Comment by kenwenzel** [comment]
Just because I am curious: What is your solution?

**Comment by iamadou** [comment]
It takes from the xml file of get_reader_config_response

**Comment by kenwenzel** [comment]
Maybe you can also simply use [XmlTypes](https://github.com/enilink/llrp4j/blob/master/llrp4j-core/src/main/java/net/enilink/llrp4j/types/XmlTypes.java) to directly convert the MAC address. This is also the utility class that is used by the XML serialization.
